# Generated by Django 4.2.11 on 2026-06-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='body_fat',
            field=models.FloatField(blank=True, null=True, verbose_name='Massa Grassa (%)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso Corporeo (kg)'),
        ),
    ]
