# Generated by Django 4.2.11 on 2026-06-08 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_body_fat_customuser_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='prezzo_mensile',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Prezzo mensile (€)'),
        ),
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'In attesa'), ('ACCEPTED', 'Accettata'), ('REJECTED', 'Rifiutata')], default='PENDING', max_length=10)),
                ('data_richiesta', models.DateTimeField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_richiesta'],
            },
        ),
    ]
