# Generated by Django 4.2.11 on 2026-06-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_prezzo_mensile_subscriptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='data_scadenza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'In attesa'), ('ACCEPTED', 'Accettata'), ('REJECTED', 'Rifiutata'), ('CANCELLED', 'Annullata'), ('EXPIRED', 'Scaduta')], default='PENDING', max_length=10),
        ),
    ]
