# Generated by Django 4.2.11 on 2026-06-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='activity_type',
            field=models.CharField(choices=[('FORZA', 'Forza / Palestra / Corpo Libero'), ('CARDIO', 'Cardio / Corsa / Bici / Nuoto')], default='FORZA', max_length=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='exercise_name',
            field=models.CharField(default='Panca Piana', help_text='Es. Panca Piana o Corsa', max_length=100, verbose_name='Nome Esercizio per calcolo'),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
