# Generated by Django 4.2.11 on 2026-06-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_goal_activity_type_goal_exercise_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='assigned_by_coach',
            field=models.BooleanField(default=False),
        ),
    ]
